query CartTransformRunInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
        }
      }
      addonVariants: attribute(key: "_addon_variants") {
        value
      }
      addonVariantsAlt: attribute(key: "addon_variants") {
        value
      }
      addons: attribute(key: "_addons") {
        value
      }
      addonsAlt: attribute(key: "addons") {
        value
      }
      addonPrice: attribute(key: "_addon_price") {
        value
      }
      addonPriceAlt: attribute(key: "addon_price") {
        value
      }
      bundleId: attribute(key: "_bundle_id") {
        value
      }
      configuredPrice: attribute(key: "_configured_price") {
        value
      }
    }
  }
}


